apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: qaxim/hello-argo:v3
        name: hello-argo
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 8081
