apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-test-app
  name: argocd-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd-test-app
  template:
    metadata:
      labels:
        app: argocd-test-app
    spec:
      containers:
      - image: qaxim/hello-argo:v1
        name: hello-argo
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-test-app-svc
spec:
  selector:
    app: argocd-test-app
  ports:
    - protocol: TCP
      port: 8081
